/** @type {import("@types/tailwindcss/tailwind-config").TailwindConfig } */

const defaultTheme = require('tailwindcss/defaultTheme');
const plugin = require('tailwindcss/plugin');

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontFamily: {
      sans: 'var(--fonts-text)',
      text: 'var(--fonts-text)',
      display: 'var(--fonts-display)',
    },
    colors: {
      white: 'var(--colors-white)',
      black: 'var(--colors-black)',
      transparent: 'var(--colors-transparent)',
      primary: {
        pink: 'var(--colors-primaryPink)',
        charcoal: 'var(--colors-primaryCharcoal)',
        blue: 'var(--colors-primaryBlue)',
        green: 'var(--colors-primaryGreen)',
        gray: 'var(--colors-primaryGray)',
      },
      secondary: {
        gray: {
          1: 'var(--colors-secondaryGrey1)',
          2: 'var(--colors-secondaryGrey2)',
          3: 'var(--colors-secondaryGrey3)',
          4: 'var(--colors-secondaryGrey4)',
        },
        purple: {
          1: 'var(--colors-secondaryPurple1)',
          2: 'var(--colors-secondaryPurple2)',
          3: 'var(--colors-secondaryPurple3)',
          4: 'var(--colors-secondaryPurple4)',
        },
        pink: {
          1: 'var(--colors-secondaryPink1)',
          2: 'var(--colors-secondaryPink2)',
          3: 'var(--colors-secondaryPink3)',
          4: 'var(--colors-secondaryPink4)',
        },
        green: {
          1: 'var(--colors-secondaryGreen1)',
          2: 'var(--colors-secondaryGreen2)',
          3: 'var(--colors-secondaryGreen3)',
          4: 'var(--colors-secondaryGreen4)',
        },
        blue: {
          1: 'var(--colors-secondaryBlue1)',
          2: 'var(--colors-secondaryBlue2)',
          3: 'var(--colors-secondaryBlue3)',
          4: 'var(--colors-secondaryBlue4)',
        },
        yellow: {
          1: 'var(--colors-secondaryYellow1)',
          2: 'var(--colors-secondaryYellow2)',
          3: 'var(--colors-secondaryYellow3)',
          4: 'var(--colors-secondaryYellow4)',
        },
      },
      red: {
        50: 'var(--colors-red50)',
        100: 'var(--colors-red100)',
        200: 'var(--colors-red200)',
        300: 'var(--colors-red300)',
        400: 'var(--colors-red400)',
        500: 'var(--colors-red500)',
        600: 'var(--colors-red600)',
        700: 'var(--colors-red700)',
        800: 'var(--colors-red800)',
        900: 'var(--colors-red900)',
      },
      gray: {
        50: 'var(--colors-gray50)',
        100: 'var(--colors-gray100)',
        200: 'var(--colors-gray200)',
        300: 'var(--colors-gray300)',
        400: 'var(--colors-gray400)',
        500: 'var(--colors-gray500)',
        600: 'var(--colors-gray600)',
        700: 'var(--colors-gray700)',
        800: 'var(--colors-gray800)',
        900: 'var(--colors-gray900)',
      },
      purple: {
        50: 'var(--colors-purple50)',
        100: 'var(--colors-purple100)',
        200: 'var(--colors-purple200)',
        300: 'var(--colors-purple300)',
        400: 'var(--colors-purple400)',
        500: 'var(--colors-purple500)',
        600: 'var(--colors-purple600)',
        700: 'var(--colors-purple700)',
        800: 'var(--colors-purple800)',
        900: 'var(--colors-purple900)',
      },
      green: {
        50: 'var(--colors-green50)',
        100: 'var(--colors-green100)',
        200: 'var(--colors-green200)',
        300: 'var(--colors-green300)',
        400: 'var(--colors-green400)',
        500: 'var(--colors-green500)',
        600: 'var(--colors-green600)',
        700: 'var(--colors-green700)',
        800: 'var(--colors-green800)',
        900: 'var(--colors-green900)',
      },
      blue: {
        50: 'var(--colors-blue50)',
        100: 'var(--colors-blue100)',
        200: 'var(--colors-blue200)',
        300: 'var(--colors-blue300)',
        400: 'var(--colors-blue400)',
        500: 'var(--colors-blue500)',
        600: 'var(--colors-blue600)',
        700: 'var(--colors-blue700)',
        800: 'var(--colors-blue800)',
        900: 'var(--colors-blue900)',
      },
      pink: {
        50: 'var(--colors-pink50)',
        100: 'var(--colors-pink100)',
        200: 'var(--colors-pink200)',
        300: 'var(--colors-pink300)',
        400: 'var(--colors-pink400)',
        500: 'var(--colors-pink500)',
        600: 'var(--colors-pink600)',
        700: 'var(--colors-pink700)',
        800: 'var(--colors-pink800)',
        900: 'var(--colors-pink900)',
      },
      yellow: {
        50: 'var(--colors-yellow50)',
        100: 'var(--colors-yellow100)',
        200: 'var(--colors-yellow200)',
        300: 'var(--colors-yellow300)',
        400: 'var(--colors-yellow400)',
        500: 'var(--colors-yellow500)',
        600: 'var(--colors-yellow600)',
        700: 'var(--colors-yellow700)',
        800: 'var(--colors-yellow800)',
        900: 'var(--colors-yellow900)',
      },

      // Tailwind anomalies
      // Indigo > mapped to purple
      indigo: {
        50: 'var(--colors-purple50)',
        100: 'var(--colors-purple100)',
        200: 'var(--colors-purple200)',
        300: 'var(--colors-purple300)',
        400: 'var(--colors-purple400)',
        500: 'var(--colors-purple500)',
        600: 'var(--colors-purple600)',
        700: 'var(--colors-purple700)',
        800: 'var(--colors-purple800)',
        900: 'var(--colors-purple900)',
      },
      lineHeight: {
        none: 'var(--lineHeights-none)',
        tight: 'var(--lineHeights-tight)',
        snug: 'var(--lineHeights-snug)',
        normal: 'var(--lineHeights-normal)',
        relaxed: 'var(--lineHeights-relaxed)',
        loose: 'var(--lineHeights-loose)',
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    plugin(function ({ addComponents }) {
      addComponents({
        '.text-hero': {
          fontFamily: 'var(--fonts-display)',
          fontSize: 'var(--fontSizes-6xl)',
          fontWeight: 'var(--fontWeights-semibold)',
          lineHeight: 'var(--lineHeights-tight)',
          letterSpacing: 'var(--letterSpacings-tighter)',
        },
        '.text-headline': {
          fontFamily: 'var(--fonts-display)',
          fontSize: 'var(--fontSizes-5xl)',
          fontWeight: 'var(--fontWeights-semibold)',
          lineHeight: 'var(--lineHeights-tight)',
          letterSpacing: 'var(--letterSpacings-tighter)',
        },
        '.text-title1': {
          fontFamily: 'var(--fonts-display)',
          fontSize: 'var(--fontSizes-4xl)',
          fontWeight: 'var(--fontWeights-semibold)',
          lineHeight: 'var(--lineHeights-tight)',
          letterSpacing: 'var(--letterSpacings-tighter)',
        },
        '.text-title2': {
          fontFamily: 'var(--fonts-display)',
          fontSize: 'var(--fontSizes-3xl)',
          fontWeight: 'var(--fontWeights-semibold)',
          lineHeight: 'var(--lineHeights-tight)',
          letterSpacing: 'var(--letterSpacings-tight)',
        },
        '.text-title3': {
          fontFamily: 'var(--fonts-display)',
          fontSize: 'var(--fontSizes-2xl)',
          fontWeight: 'var(--fontWeights-semibold)',
          lineHeight: 'var(--lineHeights-tight)',
          letterSpacing: 'var(--letterSpacings-tight)',
        },
        '.text-heading': {
          fontFamily: 'var(--fonts-display)',
          fontSize: 'var(--fontSizes-xl)',
          fontWeight: 'var(--fontWeights-medium)',
          lineHeight: 'var(--lineHeights-snug)',
          letterSpacing: 'var(--letterSpacings-tight)',
        },
        '.text-subhead': {
          fontFamily: 'var(--fonts-display)',
          fontSize: 'var(--fontSizes-lg)',
          fontWeight: 'var(--fontWeights-medium)',
          lineHeight: 'var(--lineHeights-snug)',
        },
        '.text-body': {
          fontFamily: 'var(--fonts-text)',
          fontSize: 'var(--fontSizes-base)',
          fontWeight: 'var(--fontWeights-normal)',
          lineHeight: 'var(--lineHeights-normal)',
        },
        '.text-footnote': {
          fontFamily: 'var(--fonts-text)',
          fontSize: 'var(--fontSizes-sm)',
          fontWeight: 'var(--fontWeights-normal)',
          lineHeight: 'var(--lineHeights-relaxed)',
        },
        '.text-micro': {
          fontFamily: 'var(--fonts-text)',
          fontSize: 'var(--fontSizes-xs)',
          fontWeight: 'var(--fontWeights-normal)',
          lineHeight: 'var(--lineHeights-relaxed)',
        },
      });
    }),
    require('@tailwindcss/forms'),
  ],
};
